// <auto-generated />
using InfraStructure.DbFolder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfraStructure.Migrations
{
    [DbContext(typeof(DbClass))]
    [Migration("20240229125231_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entity.MultiAttachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<string>("Attachment_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrignalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TickId")
                        .HasColumnType("int");

                    b.HasKey("AttachmentId");

                    b.HasIndex("TickId");

                    b.ToTable("MultiAttachmentTable");
                });

            modelBuilder.Entity("Domain.Entity.TicketModel", b =>
                {
                    b.Property<int>("Ticket_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ticket_Id"));

                    b.Property<string>("Category")
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Issues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority_Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ticket_Name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Ticket_Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Ticket_Id");

                    b.ToTable("TicketTable");
                });

            modelBuilder.Entity("Domain.Entity.MultiAttachment", b =>
                {
                    b.HasOne("Domain.Entity.TicketModel", "TicketModels")
                        .WithMany("MultiAttachments")
                        .HasForeignKey("TickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TicketModels");
                });

            modelBuilder.Entity("Domain.Entity.TicketModel", b =>
                {
                    b.Navigation("MultiAttachments");
                });
#pragma warning restore 612, 618
        }
    }
}
